version: '3.9'

services:
  dd-agent-dogfood-jmx:
    container_name: dd-agent-dogfood-jmx
    image: gcr.io/datadoghq/agent:latest-jmx
    hostname: dd-agent-dogfood-jmx
    environment:
      - DD_HOSTNAME=datadog
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true 
      - DD_PROCESS_AGENT_ENABLED=true 
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC="true" 
      - DD_LOG_LEVEL=debug
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"
      - SD_JMX_ENABLE=true
    ports:
     - "8125:8125"
     - "8126:8126"
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: protobuf-server
    hostname: server
    environment:
      - DD_AGENT_HOST=dd-agent-dogfood-jmx
      - DD_ENV=dev
      - DD_TRACE_ENABLED=true
      - DD_SERVICE=protobuf-server
      - DD_VERSION=1.0.0
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - LD_PRELOAD=/opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so
      - DD_DOTNET_TRACER_HOME=/opt/datadog
      - DOTNET_CLI_TELEMETRY_OPTOUT=true
      - DD_LOGS_INJECTION=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_PROFILING_ENABLED=1
    depends_on:
      - dd-agent-dogfood-jmx
    networks:
      - app-network

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: protobuf-client
    hostname: client
    environment:
      - DD_AGENT_HOST=dd-agent-dogfood-jmx
      - DD_ENV=dev
      - DD_TRACE_ENABLED=true
      - DD_SERVICE=protobuf-client
      - DD_VERSION=1.0.0
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
      - CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
      - LD_PRELOAD=/opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so
      - DD_DOTNET_TRACER_HOME=/opt/datadog
      - DOTNET_CLI_TELEMETRY_OPTOUT=true
      - DD_LOGS_INJECTION=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_PROFILING_ENABLED=1
      - SERVER_ADDRESS=server
#    stdin_open: true
#    tty: true
#    command: "bash -c 'sleep infinity'"
    depends_on:
      - server
      - dd-agent-dogfood-jmx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
